<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="SPBLRLAP-1723" failures="1" tests="2" name="TestLocal" time="12.207" errors="0" timestamp="2022-09-26T09:13:40 IST">
  <testcase classname="script.Test1" name="testA" time="0.575"/>
  <testcase classname="script.Test2" name="testB" time="0.052">
    <failure type="java.lang.AssertionError" message="expected [CONTACT ME] but found [CONTACT US]">
      <![CDATA[java.lang.AssertionError: expected [CONTACT ME] but found [CONTACT US]
at script.Test2.testB(Test2.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- testB -->
  <testcase classname="generic.BaseTest" name="@AfterSuite publishReport" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite publishReport -->
  <testcase classname="generic.BaseTest" name="@BeforeSuite initReport" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite initReport -->
</testsuite> <!-- TestLocal -->
